interface ImportMetaEnv {
	VITE_APIKEY: string;
	VITE_AUTHDOMAIN: string;
	VITE_PROJECTID: string;
	VITE_STORAGEBUCKET: string;
	VITE_DATABASE_URL: string;
	VITE_MESSAGESENDERID: string;
	VITE_APPID: string;
	VITE_MEASUREMENTID: string;
	VITE_SERVICE_ACCOUNT_JSON: string;
	VITE_SERVICE_ACCOUNT_PRIV_KEY: string;
}
